config/routes.rb
Rails.application.routes.draw do
root "departments#index" 

resources :departments do
  resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :items
    
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]


  def index
    @departments = Department.all
  end

  def show
  end

  def new
    @department = Department.new
    render partial: "form"
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to departments_path
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @department.update(department_params)
      redirect_to department_path(@department)
    else
      render :edit
    end
  end

  def destroy
    @department.destroy
    redirect_to departments_path
  end

  private

  def department_params
    params.require(:department).permit(:name)
  end

  def set_department
    @department = Department.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_department
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = @department.items
  end

  def show
  end

  def new
    @item = @department.items.new

    render partial: "form"
  end

  def create
    @item = @department.items.new(item_params)
    if @item.save
      redirect_to department_items_path(@department)
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @item.update(item_params)
      redirect_to department_item_path(@department, @item)
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to department_items_path(@department)
  end

  private
  def set_department
    @department = Department.find(params[:department_id])
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/departments/_form.html.erb
<h1><%= @department.id ? "Edit Department" : "New Department" %></h1>
<hr />
<%= form_for @department do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, required: true, autofocus: true %>

    <%= f.submit %>
    <% end %>

app/views/departments/edit.html.erb
<h1>Departments#edit</h1>
<p>Find me in app/views/departments/edit.html.erb</p>

app/views/departments/index.html.erb
<h1>Pick a Department to View its Items!</h1>
<%= link_to "Create New Department", new_department_path %>
<hr />
<h3><%= @departments.length === 0 ? "No Departments Added" : "" %></h3>
<ul>
    <% @departments.each do |department| %>
        <li> <%= link_to department.name, department_path(department) %> </li>
        <% end %>

</ul>

app/views/departments/new.html.erb
<h1>Departments#new</h1>
<p>Find me in app/views/departments/new.html.erb</p>

app/views/departments/show.html.erb
<h1><%= @department.name %></h1>
<%= link_to "Edit", edit_department_path(@department) %>
<%= link_to "Back", departments_path %>
<%= link_to "Delete", department_path(@department), method: :delete %>
<hr />
<h3>Well, you don't really have any other option, so you should probably just:</h3>

<%= link_to "View Items", department_items_path(@department) %>

app/views/items/_form.html.erb
<h1><%= @item.id ? "Edit Item" : "New Item" %></h1>
<hr />
<%= form_for [@department, @item]  do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, required: true, autofocus: true %>

    <%= f.label :body %>
    <%= f.text_area :body, required: true, autofocus: true %>


    <%= f.submit %>
    <% end %>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h1>Items!</h1>
<%= link_to "Create New Item", new_department_item_path(@department) %>
<hr />
<h3><%= @items.length === 0 ? "No Items Added" : "" %></h3>

<ul>
    <% @items.each do |item| %>
        <li><%= link_to item.name, department_item_path(@department, item) %></li>
<% end %>
</ul>

<%= link_to "Back", department_path(@department) %>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>
<%= link_to "Edit", edit_department_item_path(@department, @item) %>
<%= link_to "Back", department_items_path(@department) %>
<hr />
<p><%= @item.body %></p>

<%= link_to "Delete Item", department_item_path(@department, @item), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>